# Generated by Django 5.2.4 on 2025-09-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Reader', 'Reader'), ('Author', 'Author'), ('Admin', 'Admin')], default='Reader', max_length=20),
        ),
    ]
